services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-daguser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dagpassword}
      POSTGRES_DB: ${POSTGRES_DB:-dagdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-daguser} -d ${POSTGRES_DB:-dagdb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - backend

  dag_service:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-daguser}:${POSTGRES_PASSWORD:-dagpassword}@db:5432/${POSTGRES_DB:-dagdb}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend


volumes:
  postgres_data:


networks:
  backend:
    driver: bridge